### ISSUE TITLE
BUG: No module named conda.cliconda

### ISSUE THREAD

**Issue by karllandheer** [FMRIB-Software-Library/support#19]
Error when running fslinstaller.py file conda on Ubuntu 20.04.6 LTS. Was working fine yesterday, my guess is conda updated something? Version FSL 6.0.7.6 is being selected

#### last part of Log file here
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
17:04:34 fslinstaller.py: 937:  [stdout]: 
17:04:34 fslinstaller.py: 937:  [stdout]: 
17:12:31 fslinstaller.py: 937:  [stdout]: 
17:12:31 fslinstaller.py: 937:  [stdout]: Downloading and Extracting Packages
17:12:31 fslinstaller.py: 937:  [stdout]: 
17:12:37 fslinstaller.py: 937:  [stdout]: Preparing transaction: ...working... done
17:13:18 fslinstaller.py: 937:  [stdout]: Verifying transaction: ...working... done
17:16:13 fslinstaller.py: 937:  [stdout]: Executing transaction: ...working...
17:16:13 fslinstaller.py: 937:  [stdout]: 
17:16:13 fslinstaller.py: 937:  [stdout]: done
17:16:14 fslinstaller.py: 937:  [stdout]: #
17:16:14 fslinstaller.py: 937:  [stdout]: # To activate this environment, use
17:16:14 fslinstaller.py: 937:  [stdout]: #
17:16:14 fslinstaller.py: 937:  [stdout]: #     $ conda activate base
17:16:14 fslinstaller.py: 937:  [stdout]: #
17:16:14 fslinstaller.py: 937:  [stdout]: # To deactivate an active environment, use
17:16:14 fslinstaller.py: 937:  [stdout]: #
17:16:14 fslinstaller.py: 937:  [stdout]: #     $ conda deactivate
17:16:14 fslinstaller.py: 937:  [stdout]: 
17:16:15 fslinstaller.py: 768: Running cp fslversion /usr/local/fsl/etc [as admin: False]
17:16:15 fslinstaller.py: 768: Running cp /tmp/tmp4onmsein/fsl-6.0.7.6_linux-64.yml /usr/local/fsl/etc [as admin: False]
17:16:15 fslinstaller.py: 768: Running /usr/local/fsl/bin/mamba clean -y --all [as admin: False]
17:16:16 fslinstaller.py: 937:  [stderr]: No module named 'conda.cliconda'
17:16:17 fslinstaller.py: 937:  [stderr]: 
17:16:17 fslinstaller.py: 937:  [stderr]: # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
17:16:17 fslinstaller.py: 937:  [stderr]: 
17:16:17 fslinstaller.py: 937:  [stderr]:     Traceback (most recent call last):
17:16:17 fslinstaller.py: 937:  [stderr]:       File "/usr/local/fsl/lib/python3.11/site-packages/conda/exception_handler.py", line 17, in __call__
17:16:17 fslinstaller.py: 937:  [stderr]:         return func(*args, **kwargs)
17:16:17 fslinstaller.py: 937:  [stderr]:                ^^^^^^^^^^^^^^^^^^^^^
17:16:17 fslinstaller.py: 937:  [stderr]:       File "/usr/local/fsl/lib/python3.11/site-packages/mamba/mamba.py", line 956, in exception_converter
17:16:17 fslinstaller.py: 937:  [stderr]:         raise e
17:16:17 fslinstaller.py: 937:  [stderr]:       File "/usr/local/fsl/lib/python3.11/site-packages/mamba/mamba.py", line 949, in exception_converter
17:16:17 fslinstaller.py: 937:  [stderr]:         exit_code = _wrapped_main(*args, **kwargs)
17:16:17 fslinstaller.py: 937:  [stderr]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
17:16:17 fslinstaller.py: 937:  [stderr]:       File "/usr/local/fsl/lib/python3.11/site-packages/mamba/mamba.py", line 895, in _wrapped_main
17:16:17 fslinstaller.py: 937:  [stderr]:         result = do_call(parsed_args, p)
17:16:17 fslinstaller.py: 937:  [stderr]:                  ^^^^^^^^^^^^^^^^^^^^^^^
17:16:17 fslinstaller.py: 937:  [stderr]:       File "/usr/local/fsl/lib/python3.11/site-packages/mamba/mamba.py", line 758, in do_call
17:16:17 fslinstaller.py: 937:  [stderr]:         exit_code = clean(args, parser)
17:16:17 fslinstaller.py: 937:  [stderr]:                     ^^^^^^^^^^^^^^^^^^^
17:16:17 fslinstaller.py: 937:  [stderr]:       File "/usr/local/fsl/lib/python3.11/site-packages/mamba/mamba.py", line 701, in clean
17:16:17 fslinstaller.py: 937:  [stderr]:         module = import_module("conda.cli" + relative_mod, __name__.rsplit(".", 1)[0])
17:16:17 fslinstaller.py: 937:  [stderr]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
17:16:17 fslinstaller.py: 937:  [stderr]:       File "/usr/local/fsl/lib/python3.11/importlib/__init__.py", line 126, in import_module
17:16:17 fslinstaller.py: 937:  [stderr]:         return _bootstrap._gcd_import(name[level:], package, level)
17:16:17 fslinstaller.py: 937:  [stderr]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
17:16:17 fslinstaller.py: 937:  [stderr]:       File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
17:16:17 fslinstaller.py: 937:  [stderr]:       File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
17:16:17 fslinstaller.py: 937:  [stderr]:       File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
17:16:17 fslinstaller.py: 937:  [stderr]:       File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
17:16:17 fslinstaller.py: 937:  [stderr]:       File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
17:16:17 fslinstaller.py: 937:  [stderr]:       File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
17:16:17 fslinstaller.py: 937:  [stderr]:       File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
17:16:17 fslinstaller.py: 937:  [stderr]:       File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
17:16:17 fslinstaller.py: 937:  [stderr]:       File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
17:16:17 fslinstaller.py: 937:  [stderr]:       File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
17:16:17 fslinstaller.py: 937:  [stderr]:       File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
17:16:17 fslinstaller.py: 937:  [stderr]:     ModuleNotFoundError: No module named 'conda.cliconda'
17:16:17 fslinstaller.py: 937:  [stderr]: 
17:16:17 fslinstaller.py: 937:  [stderr]: `$ /usr/local/fsl/bin/mamba clean -y --all`
17:16:17 fslinstaller.py: 937:  [stderr]: 
17:16:17 fslinstaller.py: 937:  [stderr]:   environment variables:
17:16:17 fslinstaller.py: 937:  [stderr]:                  CIO_TEST=<not set>
17:16:17 fslinstaller.py: 937:  [stderr]:                CONDA_ROOT=/usr/local/fsl
17:16:17 fslinstaller.py: 937:  [stderr]:            CURL_CA_BUNDLE=<not set>
17:16:17 fslinstaller.py: 937:  [stderr]:                LD_PRELOAD=<not set>
17:16:17 fslinstaller.py: 937:  [stderr]:                      PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
17:16:17 fslinstaller.py: 937:  [stderr]:        REQUESTS_CA_BUNDLE=<not set>
17:16:17 fslinstaller.py: 937:  [stderr]:             SSL_CERT_FILE=<not set>
17:16:17 fslinstaller.py: 937:  [stderr]:              SUDO_COMMAND=/usr/bin/bash
17:16:17 fslinstaller.py: 937:  [stderr]:                  SUDO_GID=0
17:16:17 fslinstaller.py: 937:  [stderr]:                  SUDO_UID=0
17:16:17 fslinstaller.py: 937:  [stderr]:                 SUDO_USER=root
17:16:17 fslinstaller.py: 937:  [stderr]: 
17:16:17 fslinstaller.py: 937:  [stderr]:      active environment : None
17:16:17 fslinstaller.py: 937:  [stderr]:        user config file : /home/dnanexus/.condarc
17:16:17 fslinstaller.py: 937:  [stderr]:  populated config files : /usr/local/fsl/.condarc
17:16:17 fslinstaller.py: 937:  [stderr]:           conda version : 23.11.0
17:16:17 fslinstaller.py: 937:  [stderr]:     conda-build version : not installed
17:16:17 fslinstaller.py: 937:  [stderr]:          python version : 3.11.6.final.0
17:16:17 fslinstaller.py: 937:  [stderr]:                  solver : libmamba (default)
17:16:17 fslinstaller.py: 937:  [stderr]:        virtual packages : __archspec=1=skylake_avx512
17:16:17 fslinstaller.py: 937:  [stderr]:                           __conda=23.11.0=0
17:16:17 fslinstaller.py: 937:  [stderr]:                           __glibc=2.31=0
17:16:17 fslinstaller.py: 937:  [stderr]:                           __linux=5.15.0=0
17:16:17 fslinstaller.py: 937:  [stderr]:                           __unix=0=0
17:16:17 fslinstaller.py: 937:  [stderr]:        base environment : /usr/local/fsl  (writable)
17:16:17 fslinstaller.py: 937:  [stderr]:       conda av data dir : /usr/local/fsl/etc/conda
17:16:17 fslinstaller.py: 937:  [stderr]:   conda av metadata url : None
17:16:17 fslinstaller.py: 937:  [stderr]:            channel URLs : https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/linux-64
17:16:17 fslinstaller.py: 937:  [stderr]:                           https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/noarch
17:16:17 fslinstaller.py: 937:  [stderr]:                           https://conda.anaconda.org/conda-forge/linux-64
17:16:17 fslinstaller.py: 937:  [stderr]:                           https://conda.anaconda.org/conda-forge/noarch
17:16:17 fslinstaller.py: 937:  [stderr]:           package cache : /usr/local/fsl/pkgs
17:16:17 fslinstaller.py: 937:  [stderr]:        envs directories : /usr/local/fsl/envs
17:16:17 fslinstaller.py: 937:  [stderr]:                           /home/dnanexus/.conda/envs
17:16:17 fslinstaller.py: 937:  [stderr]:                platform : linux-64
17:16:17 fslinstaller.py: 937:  [stderr]:              user-agent : conda/23.11.0 requests/2.31.0 CPython/3.11.6 Linux/5.15.0-1050-aws ubuntu/20.04.6 glibc/2.31 solver/libmamba conda-libmamba-solver/23.11.1 libmambapy/1.5.4
17:16:17 fslinstaller.py: 937:  [stderr]:                 UID:GID : 0:0
17:16:17 fslinstaller.py: 937:  [stderr]:              netrc file : None
17:16:17 fslinstaller.py: 937:  [stderr]:            offline mode : False
17:16:17 fslinstaller.py: 937:  [stderr]: 
17:16:17 fslinstaller.py: 937:  [stderr]: 
17:16:17 fslinstaller.py: 937:  [stderr]: An unexpected error has occurred. Conda has prepared the above report.
17:16:17 fslinstaller.py: 937:  [stderr]: If you suspect this error is being caused by a malfunctioning plugin,
17:16:17 fslinstaller.py: 937:  [stderr]: consider using the --no-plugins option to turn off plugins.
17:16:17 fslinstaller.py: 937:  [stderr]: 
17:16:17 fslinstaller.py: 937:  [stderr]: Example: conda --no-plugins install <package>
17:16:17 fslinstaller.py: 937:  [stderr]: 
17:16:17 fslinstaller.py: 937:  [stderr]: Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
17:16:17 fslinstaller.py: 937:  [stderr]: the command line to run the command without plugins enabled.
17:16:17 fslinstaller.py: 937:  [stderr]: 
17:16:17 fslinstaller.py: 937:  [stderr]: Example: CONDA_NO_PLUGINS=true conda install <package>
17:16:17 fslinstaller.py: 937:  [stderr]: 
17:16:17 fslinstaller.py: 167: 
ERROR occurred during installation!
17:16:17 fslinstaller.py: 167:     This command returned an error: /usr/local/fsl/bin/mamba clean -y --all

17:16:17 fslinstaller.py:2309:   File "/tmp/fslinstaller.py", line 2301, in handle_error
    yield
  File "/tmp/fslinstaller.py", line 2401, in main
    post_install_cleanup(ctx, tmpdir)
  File "/tmp/fslinstaller.py", line 1824, in post_install_cleanup
    ctx.run(Process.check_call, cmd)
  File "/tmp/fslinstaller.py", line 1384, in run
    return process_func(admin=self.need_admin,
  File "/tmp/fslinstaller.py", line 845, in check_call
    raise RuntimeError('This command returned an error: ' + cmd)

17:16:17 fslinstaller.py: 167: Removing failed installation directory /usr/local/fsl
17:16:17 fslinstaller.py: 768: Running rm -r /usr/local/fsl [as admin: False]

**Comment by karllandheer** [comment]
Hello, this was resolved on its own. My guess is a conda update broke something. Leaving it here incase this happens again
